name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and upload Rust binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - i686-unknown-linux-gnu

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{ matrix.target }}

    - name: Build the binary
      run: cargo build --release --target ${{ matrix.target }}

    - name: Upload the binaries to the release
      uses: snok/build-and-upload-rust-binary@v1
      with:
        name: my-rust-binary-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/my-rust-binary
        github_token: ${{ secrets.GITHUB_TOKEN }}
